linters:
  enable:
    - errcheck
    - ineffassign
    - unused
    - typecheck
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - revive
    - gosec
    - gosimple
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - stylecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - govet
    - gocognit
    - dupword
    - errorlint
    - godot
    - gofumpt
    - nolintlint
    - nosprintfhostport
    - usetesting
    - thelper
    - wrapcheck

linters-settings:
  depguard:
    rules:
      default:
        allow:
          - $gostd
          - github.com/multiplay/go-ts3
          - github.com/mitchellh/mapstructure
          - golang.org/x/crypto/ssh
          - github.com/stretchr/testify
